stages:
  - release

.functions: &functions |

  function build_image() {
    echo "Building Dockerfile-based application..."
    docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    echo "Logging to GitLab Container Registry with CI credentials..."
    docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    echo "Pushing to GitLab Container Registry..."
    docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    echo ""
  }

before_script:
  - *functions

release-latest:
  stage: release
  image: docker:git
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - build_image()
  only:
    - master

release-stable:
  stage: release
  image: docker:git
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - build_image()
  only:
    - /^\d+-\d+-stable$/
